scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'api'
    scrape_interval: 100s
    scrape_timeout: 70s
    static_configs:
      - targets: ['host.docker.internal:3200']
