name: Run CI

on:
  push:
    branches: *
  pull_request: 
    branches: *

jobs:
  lint:
    steps:
       uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Run Eslint
        run: yarn lint

  typecheck:
    steps:
      - name: Run Typecheck
        run: yarn typecheck